apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service222
spec:
  selector:
    app: web 
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80         
    nodePort: 30007
  type: NodePort